### ISSUE TITLE
problem on python 3.11: ImportError: cannot import name 'MutableSequence' from 'collections'

### ISSUE THREAD

**Issue by laf0rge** [KOLANICH/ttyUSBSpy#1]
FYI, this is the output I'm getting on a Debian unstable system with python 3.11

```
$ python3 -m ttyUSBSpy
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/space/home/laforge/projects/git/ttyUSBSpy/ttyUSBSpy/__main__.py", line 38, in <module>
    from .core.usbrevue import *
  File "/space/home/laforge/projects/git/ttyUSBSpy/ttyUSBSpy/core/usbrevue.py", line 39, in <module>
    from collections import MutableSequence, Sequence
ImportError: cannot import name 'MutableSequence' from 'collections' (/usr/lib/python3.11/collections/__init__.py)
```

This seems related: https://github.com/CPJKU/madmom/issues/502

**Comment by KOLANICH** [comment]
Thaks, should be fixed by now.
