### ISSUE TITLE
AttributeError: type object 'Grid' has no attribute 'wxGridSelectCells'

### ISSUE THREAD

**Issue by laf0rge** [KOLANICH/ttyUSBSpy#2]
This is again on python3.11, using python3-wxgtk4.0 package version 4.2.0+dfsg-2 

```
$ python3 -m ttyUSBSpy
Start ttyUsbView
attach events
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/space/home/laforge/projects/git/ttyUSBSpy/ttyUSBSpy/__main__.py", line 855, in <module>
    main()
  File "/space/home/laforge/projects/git/ttyUSBSpy/ttyUSBSpy/__main__.py", line 849, in main
    theFrame.viewgrid()
  File "/space/home/laforge/projects/git/ttyUSBSpy/ttyUSBSpy/__main__.py", line 713, in viewgrid
    self.view = ViewPanel(self)
                ^^^^^^^^^^^^^^^
  File "/space/home/laforge/projects/git/ttyUSBSpy/ttyUSBSpy/__main__.py", line 439, in __init__
    parent.m_grid1.SetTable(self.dt, False, wx.grid.Grid.wxGridSelectCells)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Grid' has no attribute 'wxGridSelectCells'
```

**Comment by KOLANICH** [comment]
Should be fixed by now, thanks.

Please keep in mind: there are other errors. Now in the pcap parsing lib bindings. I feel like I'm going to replace it with a pure python one.
